name: Deploy to Production

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  actions: read

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest

    environment:
      name: production

    permissions:
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: version
        run: |
          version=${GITHUB_REF#refs/tags/}
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Using tag: $version"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Retag and push multi-arch images with skopeo
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          SRC_IMAGE="${DOCKER_USERNAME}/command-service:main-$(git rev-parse --short HEAD)"
          VERSION_TAG="${{ steps.version.outputs.version }}"

          skopeo copy --all \
            --src-creds $DOCKER_USERNAME:$DOCKER_PASSWORD \
            --dest-creds $DOCKER_USERNAME:$DOCKER_PASSWORD \
            docker://docker.io/$SRC_IMAGE docker://docker.io/${DOCKER_USERNAME}/command-service:$VERSION_TAG

      - name: Clone infrastructure repo
        env:
          PAT: ${{ secrets.INFRA_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:$PAT@github.com/TodoFlow-Labs/infrastructure.git infra
          cd infra

          # Update production tag in Helm values
          yq e ".commandService.image.tag = \"${{ steps.version.outputs.version }}\"" -i k8s/helm/todoflow/values.yaml

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s/helm/todoflow/values.yaml
          git commit -m "Update commandService image tag to ${{ steps.version.outputs.version }}"
          git push origin main
