name: Deploy to Production

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    tags:
      - 'v*.*.*'
    types: [completed]

permissions:
  actions: read

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      packages: read
    environment:
      name: production

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0

      # - name: Fetch all tags
      #   run: git fetch --tags

      - name: Extract version from tag
        id: version
        run: |
          # The tag from the triggering workflow run ref (refs/tags/...)
          version=${GITHUB_REF#refs/tags/}
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Using tag: $version"

      - name: Clone infrastructure repo
        env:
          PAT: ${{ secrets.INFRA_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:$PAT@github.com/TodoFlow-Labs/infrastructure.git infra
          cd infra

          # Update production tag in Helm values
          yq e ".commandService.image.tag = \"${{ steps.version.outputs.version }}\"" -i k8s/helm/todoflow/values.yaml

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s/helm/todoflow/values.yaml
          git commit -m "Update commandService image tag to ${{ steps.version.outputs.version }}"
          git push origin main
